// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ghidump.proto

package protoclasses;

public final class GhiDumpProto {
  private GhiDumpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GhiDumpMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoclasses.GhiDumpMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    boolean hasMetadata();
    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     * @return The metadata.
     */
    protoclasses.MetadataProto.MetaList getMetadata();
    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     */
    protoclasses.MetadataProto.MetaListOrBuilder getMetadataOrBuilder();

    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     * @return Whether the segments field is set.
     */
    boolean hasSegments();
    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     * @return The segments.
     */
    protoclasses.SegmentsProto.SegmentList getSegments();
    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     */
    protoclasses.SegmentsProto.SegmentListOrBuilder getSegmentsOrBuilder();

    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     * @return Whether the symbols field is set.
     */
    boolean hasSymbols();
    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     * @return The symbols.
     */
    protoclasses.SymbolsProto.SymbolsList getSymbols();
    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     */
    protoclasses.SymbolsProto.SymbolsListOrBuilder getSymbolsOrBuilder();

    /**
     * <code>.protoclasses.DataList data = 4;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.protoclasses.DataList data = 4;</code>
     * @return The data.
     */
    protoclasses.DataProto.DataList getData();
    /**
     * <code>.protoclasses.DataList data = 4;</code>
     */
    protoclasses.DataProto.DataListOrBuilder getDataOrBuilder();

    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     * @return Whether the functions field is set.
     */
    boolean hasFunctions();
    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     * @return The functions.
     */
    protoclasses.FunctionProto.FunctionsList getFunctions();
    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     */
    protoclasses.FunctionProto.FunctionsListOrBuilder getFunctionsOrBuilder();
  }
  /**
   * Protobuf type {@code protoclasses.GhiDumpMessage}
   */
  public  static final class GhiDumpMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoclasses.GhiDumpMessage)
      GhiDumpMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GhiDumpMessage.newBuilder() to construct.
    private GhiDumpMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GhiDumpMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GhiDumpMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GhiDumpMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protoclasses.MetadataProto.MetaList.Builder subBuilder = null;
              if (metadata_ != null) {
                subBuilder = metadata_.toBuilder();
              }
              metadata_ = input.readMessage(protoclasses.MetadataProto.MetaList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metadata_);
                metadata_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              protoclasses.SegmentsProto.SegmentList.Builder subBuilder = null;
              if (segments_ != null) {
                subBuilder = segments_.toBuilder();
              }
              segments_ = input.readMessage(protoclasses.SegmentsProto.SegmentList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(segments_);
                segments_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              protoclasses.SymbolsProto.SymbolsList.Builder subBuilder = null;
              if (symbols_ != null) {
                subBuilder = symbols_.toBuilder();
              }
              symbols_ = input.readMessage(protoclasses.SymbolsProto.SymbolsList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(symbols_);
                symbols_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              protoclasses.DataProto.DataList.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(protoclasses.DataProto.DataList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              protoclasses.FunctionProto.FunctionsList.Builder subBuilder = null;
              if (functions_ != null) {
                subBuilder = functions_.toBuilder();
              }
              functions_ = input.readMessage(protoclasses.FunctionProto.FunctionsList.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(functions_);
                functions_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclasses.GhiDumpProto.internal_static_protoclasses_GhiDumpMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclasses.GhiDumpProto.internal_static_protoclasses_GhiDumpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclasses.GhiDumpProto.GhiDumpMessage.class, protoclasses.GhiDumpProto.GhiDumpMessage.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private protoclasses.MetadataProto.MetaList metadata_;
    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadata_ != null;
    }
    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     * @return The metadata.
     */
    public protoclasses.MetadataProto.MetaList getMetadata() {
      return metadata_ == null ? protoclasses.MetadataProto.MetaList.getDefaultInstance() : metadata_;
    }
    /**
     * <code>.protoclasses.MetaList metadata = 1;</code>
     */
    public protoclasses.MetadataProto.MetaListOrBuilder getMetadataOrBuilder() {
      return getMetadata();
    }

    public static final int SEGMENTS_FIELD_NUMBER = 2;
    private protoclasses.SegmentsProto.SegmentList segments_;
    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     * @return Whether the segments field is set.
     */
    public boolean hasSegments() {
      return segments_ != null;
    }
    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     * @return The segments.
     */
    public protoclasses.SegmentsProto.SegmentList getSegments() {
      return segments_ == null ? protoclasses.SegmentsProto.SegmentList.getDefaultInstance() : segments_;
    }
    /**
     * <code>.protoclasses.SegmentList segments = 2;</code>
     */
    public protoclasses.SegmentsProto.SegmentListOrBuilder getSegmentsOrBuilder() {
      return getSegments();
    }

    public static final int SYMBOLS_FIELD_NUMBER = 3;
    private protoclasses.SymbolsProto.SymbolsList symbols_;
    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     * @return Whether the symbols field is set.
     */
    public boolean hasSymbols() {
      return symbols_ != null;
    }
    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     * @return The symbols.
     */
    public protoclasses.SymbolsProto.SymbolsList getSymbols() {
      return symbols_ == null ? protoclasses.SymbolsProto.SymbolsList.getDefaultInstance() : symbols_;
    }
    /**
     * <code>.protoclasses.SymbolsList symbols = 3;</code>
     */
    public protoclasses.SymbolsProto.SymbolsListOrBuilder getSymbolsOrBuilder() {
      return getSymbols();
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private protoclasses.DataProto.DataList data_;
    /**
     * <code>.protoclasses.DataList data = 4;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.protoclasses.DataList data = 4;</code>
     * @return The data.
     */
    public protoclasses.DataProto.DataList getData() {
      return data_ == null ? protoclasses.DataProto.DataList.getDefaultInstance() : data_;
    }
    /**
     * <code>.protoclasses.DataList data = 4;</code>
     */
    public protoclasses.DataProto.DataListOrBuilder getDataOrBuilder() {
      return getData();
    }

    public static final int FUNCTIONS_FIELD_NUMBER = 5;
    private protoclasses.FunctionProto.FunctionsList functions_;
    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     * @return Whether the functions field is set.
     */
    public boolean hasFunctions() {
      return functions_ != null;
    }
    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     * @return The functions.
     */
    public protoclasses.FunctionProto.FunctionsList getFunctions() {
      return functions_ == null ? protoclasses.FunctionProto.FunctionsList.getDefaultInstance() : functions_;
    }
    /**
     * <code>.protoclasses.FunctionsList functions = 5;</code>
     */
    public protoclasses.FunctionProto.FunctionsListOrBuilder getFunctionsOrBuilder() {
      return getFunctions();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (metadata_ != null) {
        output.writeMessage(1, getMetadata());
      }
      if (segments_ != null) {
        output.writeMessage(2, getSegments());
      }
      if (symbols_ != null) {
        output.writeMessage(3, getSymbols());
      }
      if (data_ != null) {
        output.writeMessage(4, getData());
      }
      if (functions_ != null) {
        output.writeMessage(5, getFunctions());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (metadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetadata());
      }
      if (segments_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSegments());
      }
      if (symbols_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSymbols());
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getData());
      }
      if (functions_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFunctions());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoclasses.GhiDumpProto.GhiDumpMessage)) {
        return super.equals(obj);
      }
      protoclasses.GhiDumpProto.GhiDumpMessage other = (protoclasses.GhiDumpProto.GhiDumpMessage) obj;

      if (hasMetadata() != other.hasMetadata()) return false;
      if (hasMetadata()) {
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
      }
      if (hasSegments() != other.hasSegments()) return false;
      if (hasSegments()) {
        if (!getSegments()
            .equals(other.getSegments())) return false;
      }
      if (hasSymbols() != other.hasSymbols()) return false;
      if (hasSymbols()) {
        if (!getSymbols()
            .equals(other.getSymbols())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (hasFunctions() != other.hasFunctions()) return false;
      if (hasFunctions()) {
        if (!getFunctions()
            .equals(other.getFunctions())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      if (hasSegments()) {
        hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getSegments().hashCode();
      }
      if (hasSymbols()) {
        hash = (37 * hash) + SYMBOLS_FIELD_NUMBER;
        hash = (53 * hash) + getSymbols().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasFunctions()) {
        hash = (37 * hash) + FUNCTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getFunctions().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.GhiDumpProto.GhiDumpMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoclasses.GhiDumpProto.GhiDumpMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclasses.GhiDumpMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoclasses.GhiDumpMessage)
        protoclasses.GhiDumpProto.GhiDumpMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclasses.GhiDumpProto.internal_static_protoclasses_GhiDumpMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclasses.GhiDumpProto.internal_static_protoclasses_GhiDumpMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclasses.GhiDumpProto.GhiDumpMessage.class, protoclasses.GhiDumpProto.GhiDumpMessage.Builder.class);
      }

      // Construct using protoclasses.GhiDumpProto.GhiDumpMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metadataBuilder_ == null) {
          metadata_ = null;
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }
        if (segmentsBuilder_ == null) {
          segments_ = null;
        } else {
          segments_ = null;
          segmentsBuilder_ = null;
        }
        if (symbolsBuilder_ == null) {
          symbols_ = null;
        } else {
          symbols_ = null;
          symbolsBuilder_ = null;
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        if (functionsBuilder_ == null) {
          functions_ = null;
        } else {
          functions_ = null;
          functionsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclasses.GhiDumpProto.internal_static_protoclasses_GhiDumpMessage_descriptor;
      }

      @java.lang.Override
      public protoclasses.GhiDumpProto.GhiDumpMessage getDefaultInstanceForType() {
        return protoclasses.GhiDumpProto.GhiDumpMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protoclasses.GhiDumpProto.GhiDumpMessage build() {
        protoclasses.GhiDumpProto.GhiDumpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoclasses.GhiDumpProto.GhiDumpMessage buildPartial() {
        protoclasses.GhiDumpProto.GhiDumpMessage result = new protoclasses.GhiDumpProto.GhiDumpMessage(this);
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        if (segmentsBuilder_ == null) {
          result.segments_ = segments_;
        } else {
          result.segments_ = segmentsBuilder_.build();
        }
        if (symbolsBuilder_ == null) {
          result.symbols_ = symbols_;
        } else {
          result.symbols_ = symbolsBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (functionsBuilder_ == null) {
          result.functions_ = functions_;
        } else {
          result.functions_ = functionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclasses.GhiDumpProto.GhiDumpMessage) {
          return mergeFrom((protoclasses.GhiDumpProto.GhiDumpMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclasses.GhiDumpProto.GhiDumpMessage other) {
        if (other == protoclasses.GhiDumpProto.GhiDumpMessage.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        if (other.hasSegments()) {
          mergeSegments(other.getSegments());
        }
        if (other.hasSymbols()) {
          mergeSymbols(other.getSymbols());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.hasFunctions()) {
          mergeFunctions(other.getFunctions());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclasses.GhiDumpProto.GhiDumpMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclasses.GhiDumpProto.GhiDumpMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private protoclasses.MetadataProto.MetaList metadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.MetadataProto.MetaList, protoclasses.MetadataProto.MetaList.Builder, protoclasses.MetadataProto.MetaListOrBuilder> metadataBuilder_;
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       * @return Whether the metadata field is set.
       */
      public boolean hasMetadata() {
        return metadataBuilder_ != null || metadata_ != null;
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       * @return The metadata.
       */
      public protoclasses.MetadataProto.MetaList getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? protoclasses.MetadataProto.MetaList.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public Builder setMetadata(protoclasses.MetadataProto.MetaList value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
          onChanged();
        } else {
          metadataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public Builder setMetadata(
          protoclasses.MetadataProto.MetaList.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
          onChanged();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public Builder mergeMetadata(protoclasses.MetadataProto.MetaList value) {
        if (metadataBuilder_ == null) {
          if (metadata_ != null) {
            metadata_ =
              protoclasses.MetadataProto.MetaList.newBuilder(metadata_).mergeFrom(value).buildPartial();
          } else {
            metadata_ = value;
          }
          onChanged();
        } else {
          metadataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = null;
          onChanged();
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public protoclasses.MetadataProto.MetaList.Builder getMetadataBuilder() {
        
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      public protoclasses.MetadataProto.MetaListOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              protoclasses.MetadataProto.MetaList.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>.protoclasses.MetaList metadata = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.MetadataProto.MetaList, protoclasses.MetadataProto.MetaList.Builder, protoclasses.MetadataProto.MetaListOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protoclasses.MetadataProto.MetaList, protoclasses.MetadataProto.MetaList.Builder, protoclasses.MetadataProto.MetaListOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }

      private protoclasses.SegmentsProto.SegmentList segments_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.SegmentsProto.SegmentList, protoclasses.SegmentsProto.SegmentList.Builder, protoclasses.SegmentsProto.SegmentListOrBuilder> segmentsBuilder_;
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       * @return Whether the segments field is set.
       */
      public boolean hasSegments() {
        return segmentsBuilder_ != null || segments_ != null;
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       * @return The segments.
       */
      public protoclasses.SegmentsProto.SegmentList getSegments() {
        if (segmentsBuilder_ == null) {
          return segments_ == null ? protoclasses.SegmentsProto.SegmentList.getDefaultInstance() : segments_;
        } else {
          return segmentsBuilder_.getMessage();
        }
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public Builder setSegments(protoclasses.SegmentsProto.SegmentList value) {
        if (segmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          segments_ = value;
          onChanged();
        } else {
          segmentsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public Builder setSegments(
          protoclasses.SegmentsProto.SegmentList.Builder builderForValue) {
        if (segmentsBuilder_ == null) {
          segments_ = builderForValue.build();
          onChanged();
        } else {
          segmentsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public Builder mergeSegments(protoclasses.SegmentsProto.SegmentList value) {
        if (segmentsBuilder_ == null) {
          if (segments_ != null) {
            segments_ =
              protoclasses.SegmentsProto.SegmentList.newBuilder(segments_).mergeFrom(value).buildPartial();
          } else {
            segments_ = value;
          }
          onChanged();
        } else {
          segmentsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public Builder clearSegments() {
        if (segmentsBuilder_ == null) {
          segments_ = null;
          onChanged();
        } else {
          segments_ = null;
          segmentsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public protoclasses.SegmentsProto.SegmentList.Builder getSegmentsBuilder() {
        
        onChanged();
        return getSegmentsFieldBuilder().getBuilder();
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      public protoclasses.SegmentsProto.SegmentListOrBuilder getSegmentsOrBuilder() {
        if (segmentsBuilder_ != null) {
          return segmentsBuilder_.getMessageOrBuilder();
        } else {
          return segments_ == null ?
              protoclasses.SegmentsProto.SegmentList.getDefaultInstance() : segments_;
        }
      }
      /**
       * <code>.protoclasses.SegmentList segments = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.SegmentsProto.SegmentList, protoclasses.SegmentsProto.SegmentList.Builder, protoclasses.SegmentsProto.SegmentListOrBuilder> 
          getSegmentsFieldBuilder() {
        if (segmentsBuilder_ == null) {
          segmentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protoclasses.SegmentsProto.SegmentList, protoclasses.SegmentsProto.SegmentList.Builder, protoclasses.SegmentsProto.SegmentListOrBuilder>(
                  getSegments(),
                  getParentForChildren(),
                  isClean());
          segments_ = null;
        }
        return segmentsBuilder_;
      }

      private protoclasses.SymbolsProto.SymbolsList symbols_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.SymbolsProto.SymbolsList, protoclasses.SymbolsProto.SymbolsList.Builder, protoclasses.SymbolsProto.SymbolsListOrBuilder> symbolsBuilder_;
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       * @return Whether the symbols field is set.
       */
      public boolean hasSymbols() {
        return symbolsBuilder_ != null || symbols_ != null;
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       * @return The symbols.
       */
      public protoclasses.SymbolsProto.SymbolsList getSymbols() {
        if (symbolsBuilder_ == null) {
          return symbols_ == null ? protoclasses.SymbolsProto.SymbolsList.getDefaultInstance() : symbols_;
        } else {
          return symbolsBuilder_.getMessage();
        }
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public Builder setSymbols(protoclasses.SymbolsProto.SymbolsList value) {
        if (symbolsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          symbols_ = value;
          onChanged();
        } else {
          symbolsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public Builder setSymbols(
          protoclasses.SymbolsProto.SymbolsList.Builder builderForValue) {
        if (symbolsBuilder_ == null) {
          symbols_ = builderForValue.build();
          onChanged();
        } else {
          symbolsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public Builder mergeSymbols(protoclasses.SymbolsProto.SymbolsList value) {
        if (symbolsBuilder_ == null) {
          if (symbols_ != null) {
            symbols_ =
              protoclasses.SymbolsProto.SymbolsList.newBuilder(symbols_).mergeFrom(value).buildPartial();
          } else {
            symbols_ = value;
          }
          onChanged();
        } else {
          symbolsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public Builder clearSymbols() {
        if (symbolsBuilder_ == null) {
          symbols_ = null;
          onChanged();
        } else {
          symbols_ = null;
          symbolsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public protoclasses.SymbolsProto.SymbolsList.Builder getSymbolsBuilder() {
        
        onChanged();
        return getSymbolsFieldBuilder().getBuilder();
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      public protoclasses.SymbolsProto.SymbolsListOrBuilder getSymbolsOrBuilder() {
        if (symbolsBuilder_ != null) {
          return symbolsBuilder_.getMessageOrBuilder();
        } else {
          return symbols_ == null ?
              protoclasses.SymbolsProto.SymbolsList.getDefaultInstance() : symbols_;
        }
      }
      /**
       * <code>.protoclasses.SymbolsList symbols = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.SymbolsProto.SymbolsList, protoclasses.SymbolsProto.SymbolsList.Builder, protoclasses.SymbolsProto.SymbolsListOrBuilder> 
          getSymbolsFieldBuilder() {
        if (symbolsBuilder_ == null) {
          symbolsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protoclasses.SymbolsProto.SymbolsList, protoclasses.SymbolsProto.SymbolsList.Builder, protoclasses.SymbolsProto.SymbolsListOrBuilder>(
                  getSymbols(),
                  getParentForChildren(),
                  isClean());
          symbols_ = null;
        }
        return symbolsBuilder_;
      }

      private protoclasses.DataProto.DataList data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.DataProto.DataList, protoclasses.DataProto.DataList.Builder, protoclasses.DataProto.DataListOrBuilder> dataBuilder_;
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       * @return Whether the data field is set.
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       * @return The data.
       */
      public protoclasses.DataProto.DataList getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? protoclasses.DataProto.DataList.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public Builder setData(protoclasses.DataProto.DataList value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public Builder setData(
          protoclasses.DataProto.DataList.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public Builder mergeData(protoclasses.DataProto.DataList value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              protoclasses.DataProto.DataList.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public protoclasses.DataProto.DataList.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      public protoclasses.DataProto.DataListOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              protoclasses.DataProto.DataList.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.protoclasses.DataList data = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.DataProto.DataList, protoclasses.DataProto.DataList.Builder, protoclasses.DataProto.DataListOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protoclasses.DataProto.DataList, protoclasses.DataProto.DataList.Builder, protoclasses.DataProto.DataListOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private protoclasses.FunctionProto.FunctionsList functions_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.FunctionProto.FunctionsList, protoclasses.FunctionProto.FunctionsList.Builder, protoclasses.FunctionProto.FunctionsListOrBuilder> functionsBuilder_;
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       * @return Whether the functions field is set.
       */
      public boolean hasFunctions() {
        return functionsBuilder_ != null || functions_ != null;
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       * @return The functions.
       */
      public protoclasses.FunctionProto.FunctionsList getFunctions() {
        if (functionsBuilder_ == null) {
          return functions_ == null ? protoclasses.FunctionProto.FunctionsList.getDefaultInstance() : functions_;
        } else {
          return functionsBuilder_.getMessage();
        }
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public Builder setFunctions(protoclasses.FunctionProto.FunctionsList value) {
        if (functionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          functions_ = value;
          onChanged();
        } else {
          functionsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public Builder setFunctions(
          protoclasses.FunctionProto.FunctionsList.Builder builderForValue) {
        if (functionsBuilder_ == null) {
          functions_ = builderForValue.build();
          onChanged();
        } else {
          functionsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public Builder mergeFunctions(protoclasses.FunctionProto.FunctionsList value) {
        if (functionsBuilder_ == null) {
          if (functions_ != null) {
            functions_ =
              protoclasses.FunctionProto.FunctionsList.newBuilder(functions_).mergeFrom(value).buildPartial();
          } else {
            functions_ = value;
          }
          onChanged();
        } else {
          functionsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public Builder clearFunctions() {
        if (functionsBuilder_ == null) {
          functions_ = null;
          onChanged();
        } else {
          functions_ = null;
          functionsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public protoclasses.FunctionProto.FunctionsList.Builder getFunctionsBuilder() {
        
        onChanged();
        return getFunctionsFieldBuilder().getBuilder();
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      public protoclasses.FunctionProto.FunctionsListOrBuilder getFunctionsOrBuilder() {
        if (functionsBuilder_ != null) {
          return functionsBuilder_.getMessageOrBuilder();
        } else {
          return functions_ == null ?
              protoclasses.FunctionProto.FunctionsList.getDefaultInstance() : functions_;
        }
      }
      /**
       * <code>.protoclasses.FunctionsList functions = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protoclasses.FunctionProto.FunctionsList, protoclasses.FunctionProto.FunctionsList.Builder, protoclasses.FunctionProto.FunctionsListOrBuilder> 
          getFunctionsFieldBuilder() {
        if (functionsBuilder_ == null) {
          functionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protoclasses.FunctionProto.FunctionsList, protoclasses.FunctionProto.FunctionsList.Builder, protoclasses.FunctionProto.FunctionsListOrBuilder>(
                  getFunctions(),
                  getParentForChildren(),
                  isClean());
          functions_ = null;
        }
        return functionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoclasses.GhiDumpMessage)
    }

    // @@protoc_insertion_point(class_scope:protoclasses.GhiDumpMessage)
    private static final protoclasses.GhiDumpProto.GhiDumpMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoclasses.GhiDumpProto.GhiDumpMessage();
    }

    public static protoclasses.GhiDumpProto.GhiDumpMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GhiDumpMessage>
        PARSER = new com.google.protobuf.AbstractParser<GhiDumpMessage>() {
      @java.lang.Override
      public GhiDumpMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GhiDumpMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GhiDumpMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GhiDumpMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoclasses.GhiDumpProto.GhiDumpMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclasses_GhiDumpMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoclasses_GhiDumpMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rghidump.proto\022\014protoclasses\032\016metadata." +
      "proto\032\016segments.proto\032\rsymbols.proto\032\nda" +
      "ta.proto\032\016function.proto\"\351\001\n\016GhiDumpMess" +
      "age\022(\n\010metadata\030\001 \001(\0132\026.protoclasses.Met" +
      "aList\022+\n\010segments\030\002 \001(\0132\031.protoclasses.S" +
      "egmentList\022*\n\007symbols\030\003 \001(\0132\031.protoclass" +
      "es.SymbolsList\022$\n\004data\030\004 \001(\0132\026.protoclas" +
      "ses.DataList\022.\n\tfunctions\030\005 \001(\0132\033.protoc" +
      "lasses.FunctionsListB\016B\014GhiDumpProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protoclasses.MetadataProto.getDescriptor(),
          protoclasses.SegmentsProto.getDescriptor(),
          protoclasses.SymbolsProto.getDescriptor(),
          protoclasses.DataProto.getDescriptor(),
          protoclasses.FunctionProto.getDescriptor(),
        });
    internal_static_protoclasses_GhiDumpMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoclasses_GhiDumpMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoclasses_GhiDumpMessage_descriptor,
        new java.lang.String[] { "Metadata", "Segments", "Symbols", "Data", "Functions", });
    protoclasses.MetadataProto.getDescriptor();
    protoclasses.SegmentsProto.getDescriptor();
    protoclasses.SymbolsProto.getDescriptor();
    protoclasses.DataProto.getDescriptor();
    protoclasses.FunctionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
