// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kindofdata.proto

package protoclasses;

public final class KindOfData {
  private KindOfData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protoclasses.DataKind}
   */
  public enum DataKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFINED = 0;</code>
     */
    DEFINED(0),
    /**
     * <code>STRING = 1;</code>
     */
    STRING(1),
    /**
     * <code>ARRAY = 2;</code>
     */
    ARRAY(2),
    /**
     * <code>CONSTANT = 3;</code>
     */
    CONSTANT(3),
    /**
     * <code>DYNAMIC = 4;</code>
     */
    DYNAMIC(4),
    /**
     * <code>POINTER = 5;</code>
     */
    POINTER(5),
    /**
     * <code>STRUCTURE = 6;</code>
     */
    STRUCTURE(6),
    /**
     * <code>UNION = 7;</code>
     */
    UNION(7),
    /**
     * <code>VOLATILE = 8;</code>
     */
    VOLATILE(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFINED = 0;</code>
     */
    public static final int DEFINED_VALUE = 0;
    /**
     * <code>STRING = 1;</code>
     */
    public static final int STRING_VALUE = 1;
    /**
     * <code>ARRAY = 2;</code>
     */
    public static final int ARRAY_VALUE = 2;
    /**
     * <code>CONSTANT = 3;</code>
     */
    public static final int CONSTANT_VALUE = 3;
    /**
     * <code>DYNAMIC = 4;</code>
     */
    public static final int DYNAMIC_VALUE = 4;
    /**
     * <code>POINTER = 5;</code>
     */
    public static final int POINTER_VALUE = 5;
    /**
     * <code>STRUCTURE = 6;</code>
     */
    public static final int STRUCTURE_VALUE = 6;
    /**
     * <code>UNION = 7;</code>
     */
    public static final int UNION_VALUE = 7;
    /**
     * <code>VOLATILE = 8;</code>
     */
    public static final int VOLATILE_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataKind valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataKind forNumber(int value) {
      switch (value) {
        case 0: return DEFINED;
        case 1: return STRING;
        case 2: return ARRAY;
        case 3: return CONSTANT;
        case 4: return DYNAMIC;
        case 5: return POINTER;
        case 6: return STRUCTURE;
        case 7: return UNION;
        case 8: return VOLATILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataKind>() {
            public DataKind findValueByNumber(int number) {
              return DataKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protoclasses.KindOfData.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataKind[] VALUES = values();

    public static DataKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protoclasses.DataKind)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020kindofdata.proto\022\014protoclasses*~\n\010Data" +
      "Kind\022\013\n\007DEFINED\020\000\022\n\n\006STRING\020\001\022\t\n\005ARRAY\020\002" +
      "\022\014\n\010CONSTANT\020\003\022\013\n\007DYNAMIC\020\004\022\013\n\007POINTER\020\005" +
      "\022\r\n\tSTRUCTURE\020\006\022\t\n\005UNION\020\007\022\014\n\010VOLATILE\020\010" +
      "B\014B\nKindOfDatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
