// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labels.proto

package protoclasses;

public final class LabelsProto {
  private LabelsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LabelMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoclasses.LabelMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 int_label = 1;</code>
     * @return The intLabel.
     */
    long getIntLabel();

    /**
     * <code>string symbolic_label = 2;</code>
     * @return The symbolicLabel.
     */
    java.lang.String getSymbolicLabel();
    /**
     * <code>string symbolic_label = 2;</code>
     * @return The bytes for symbolicLabel.
     */
    com.google.protobuf.ByteString
        getSymbolicLabelBytes();

    /**
     * <code>int32 label_id = 3;</code>
     * @return The labelId.
     */
    int getLabelId();

    public protoclasses.LabelsProto.LabelMessage.LabelCase getLabelCase();
  }
  /**
   * Protobuf type {@code protoclasses.LabelMessage}
   */
  public  static final class LabelMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoclasses.LabelMessage)
      LabelMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LabelMessage.newBuilder() to construct.
    private LabelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LabelMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LabelMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LabelMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              labelCase_ = 1;
              label_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              labelCase_ = 2;
              label_ = s;
              break;
            }
            case 24: {

              labelId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclasses.LabelsProto.internal_static_protoclasses_LabelMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclasses.LabelsProto.internal_static_protoclasses_LabelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclasses.LabelsProto.LabelMessage.class, protoclasses.LabelsProto.LabelMessage.Builder.class);
    }

    private int labelCase_ = 0;
    private java.lang.Object label_;
    public enum LabelCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INT_LABEL(1),
      SYMBOLIC_LABEL(2),
      LABEL_NOT_SET(0);
      private final int value;
      private LabelCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static LabelCase valueOf(int value) {
        return forNumber(value);
      }

      public static LabelCase forNumber(int value) {
        switch (value) {
          case 1: return INT_LABEL;
          case 2: return SYMBOLIC_LABEL;
          case 0: return LABEL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public LabelCase
    getLabelCase() {
      return LabelCase.forNumber(
          labelCase_);
    }

    public static final int INT_LABEL_FIELD_NUMBER = 1;
    /**
     * <code>uint64 int_label = 1;</code>
     * @return The intLabel.
     */
    public long getIntLabel() {
      if (labelCase_ == 1) {
        return (java.lang.Long) label_;
      }
      return 0L;
    }

    public static final int SYMBOLIC_LABEL_FIELD_NUMBER = 2;
    /**
     * <code>string symbolic_label = 2;</code>
     * @return The symbolicLabel.
     */
    public java.lang.String getSymbolicLabel() {
      java.lang.Object ref = "";
      if (labelCase_ == 2) {
        ref = label_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (labelCase_ == 2) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string symbolic_label = 2;</code>
     * @return The bytes for symbolicLabel.
     */
    public com.google.protobuf.ByteString
        getSymbolicLabelBytes() {
      java.lang.Object ref = "";
      if (labelCase_ == 2) {
        ref = label_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (labelCase_ == 2) {
          label_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_ID_FIELD_NUMBER = 3;
    private int labelId_;
    /**
     * <code>int32 label_id = 3;</code>
     * @return The labelId.
     */
    public int getLabelId() {
      return labelId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (labelCase_ == 1) {
        output.writeUInt64(
            1, (long)((java.lang.Long) label_));
      }
      if (labelCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
      if (labelId_ != 0) {
        output.writeInt32(3, labelId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (labelCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(
              1, (long)((java.lang.Long) label_));
      }
      if (labelCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      if (labelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, labelId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoclasses.LabelsProto.LabelMessage)) {
        return super.equals(obj);
      }
      protoclasses.LabelsProto.LabelMessage other = (protoclasses.LabelsProto.LabelMessage) obj;

      if (getLabelId()
          != other.getLabelId()) return false;
      if (!getLabelCase().equals(other.getLabelCase())) return false;
      switch (labelCase_) {
        case 1:
          if (getIntLabel()
              != other.getIntLabel()) return false;
          break;
        case 2:
          if (!getSymbolicLabel()
              .equals(other.getSymbolicLabel())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLabelId();
      switch (labelCase_) {
        case 1:
          hash = (37 * hash) + INT_LABEL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getIntLabel());
          break;
        case 2:
          hash = (37 * hash) + SYMBOLIC_LABEL_FIELD_NUMBER;
          hash = (53 * hash) + getSymbolicLabel().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoclasses.LabelsProto.LabelMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclasses.LabelMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoclasses.LabelMessage)
        protoclasses.LabelsProto.LabelMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclasses.LabelsProto.LabelMessage.class, protoclasses.LabelsProto.LabelMessage.Builder.class);
      }

      // Construct using protoclasses.LabelsProto.LabelMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        labelId_ = 0;

        labelCase_ = 0;
        label_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelMessage_descriptor;
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelMessage getDefaultInstanceForType() {
        return protoclasses.LabelsProto.LabelMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelMessage build() {
        protoclasses.LabelsProto.LabelMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelMessage buildPartial() {
        protoclasses.LabelsProto.LabelMessage result = new protoclasses.LabelsProto.LabelMessage(this);
        if (labelCase_ == 1) {
          result.label_ = label_;
        }
        if (labelCase_ == 2) {
          result.label_ = label_;
        }
        result.labelId_ = labelId_;
        result.labelCase_ = labelCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclasses.LabelsProto.LabelMessage) {
          return mergeFrom((protoclasses.LabelsProto.LabelMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclasses.LabelsProto.LabelMessage other) {
        if (other == protoclasses.LabelsProto.LabelMessage.getDefaultInstance()) return this;
        if (other.getLabelId() != 0) {
          setLabelId(other.getLabelId());
        }
        switch (other.getLabelCase()) {
          case INT_LABEL: {
            setIntLabel(other.getIntLabel());
            break;
          }
          case SYMBOLIC_LABEL: {
            labelCase_ = 2;
            label_ = other.label_;
            onChanged();
            break;
          }
          case LABEL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclasses.LabelsProto.LabelMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclasses.LabelsProto.LabelMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int labelCase_ = 0;
      private java.lang.Object label_;
      public LabelCase
          getLabelCase() {
        return LabelCase.forNumber(
            labelCase_);
      }

      public Builder clearLabel() {
        labelCase_ = 0;
        label_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>uint64 int_label = 1;</code>
       * @return The intLabel.
       */
      public long getIntLabel() {
        if (labelCase_ == 1) {
          return (java.lang.Long) label_;
        }
        return 0L;
      }
      /**
       * <code>uint64 int_label = 1;</code>
       * @param value The intLabel to set.
       * @return This builder for chaining.
       */
      public Builder setIntLabel(long value) {
        labelCase_ = 1;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 int_label = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntLabel() {
        if (labelCase_ == 1) {
          labelCase_ = 0;
          label_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string symbolic_label = 2;</code>
       * @return The symbolicLabel.
       */
      public java.lang.String getSymbolicLabel() {
        java.lang.Object ref = "";
        if (labelCase_ == 2) {
          ref = label_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (labelCase_ == 2) {
            label_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbolic_label = 2;</code>
       * @return The bytes for symbolicLabel.
       */
      public com.google.protobuf.ByteString
          getSymbolicLabelBytes() {
        java.lang.Object ref = "";
        if (labelCase_ == 2) {
          ref = label_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (labelCase_ == 2) {
            label_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbolic_label = 2;</code>
       * @param value The symbolicLabel to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolicLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  labelCase_ = 2;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbolic_label = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbolicLabel() {
        if (labelCase_ == 2) {
          labelCase_ = 0;
          label_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string symbolic_label = 2;</code>
       * @param value The bytes for symbolicLabel to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolicLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        labelCase_ = 2;
        label_ = value;
        onChanged();
        return this;
      }

      private int labelId_ ;
      /**
       * <code>int32 label_id = 3;</code>
       * @return The labelId.
       */
      public int getLabelId() {
        return labelId_;
      }
      /**
       * <code>int32 label_id = 3;</code>
       * @param value The labelId to set.
       * @return This builder for chaining.
       */
      public Builder setLabelId(int value) {
        
        labelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 label_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabelId() {
        
        labelId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoclasses.LabelMessage)
    }

    // @@protoc_insertion_point(class_scope:protoclasses.LabelMessage)
    private static final protoclasses.LabelsProto.LabelMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoclasses.LabelsProto.LabelMessage();
    }

    public static protoclasses.LabelsProto.LabelMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LabelMessage>
        PARSER = new com.google.protobuf.AbstractParser<LabelMessage>() {
      @java.lang.Override
      public LabelMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LabelMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LabelMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LabelMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoclasses.LabelsProto.LabelMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LabelsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoclasses.LabelsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    java.util.List<protoclasses.LabelsProto.LabelMessage> 
        getLabelsList();
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    protoclasses.LabelsProto.LabelMessage getLabels(int index);
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    int getLabelsCount();
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    java.util.List<? extends protoclasses.LabelsProto.LabelMessageOrBuilder> 
        getLabelsOrBuilderList();
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    protoclasses.LabelsProto.LabelMessageOrBuilder getLabelsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoclasses.LabelsList}
   */
  public  static final class LabelsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoclasses.LabelsList)
      LabelsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LabelsList.newBuilder() to construct.
    private LabelsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LabelsList() {
      labels_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LabelsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LabelsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                labels_ = new java.util.ArrayList<protoclasses.LabelsProto.LabelMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              labels_.add(
                  input.readMessage(protoclasses.LabelsProto.LabelMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclasses.LabelsProto.internal_static_protoclasses_LabelsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclasses.LabelsProto.internal_static_protoclasses_LabelsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclasses.LabelsProto.LabelsList.class, protoclasses.LabelsProto.LabelsList.Builder.class);
    }

    public static final int LABELS_FIELD_NUMBER = 1;
    private java.util.List<protoclasses.LabelsProto.LabelMessage> labels_;
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    public java.util.List<protoclasses.LabelsProto.LabelMessage> getLabelsList() {
      return labels_;
    }
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    public java.util.List<? extends protoclasses.LabelsProto.LabelMessageOrBuilder> 
        getLabelsOrBuilderList() {
      return labels_;
    }
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    public protoclasses.LabelsProto.LabelMessage getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
     */
    public protoclasses.LabelsProto.LabelMessageOrBuilder getLabelsOrBuilder(
        int index) {
      return labels_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < labels_.size(); i++) {
        output.writeMessage(1, labels_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < labels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, labels_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoclasses.LabelsProto.LabelsList)) {
        return super.equals(obj);
      }
      protoclasses.LabelsProto.LabelsList other = (protoclasses.LabelsProto.LabelsList) obj;

      if (!getLabelsList()
          .equals(other.getLabelsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLabelsCount() > 0) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + getLabelsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoclasses.LabelsProto.LabelsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.LabelsProto.LabelsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoclasses.LabelsProto.LabelsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclasses.LabelsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoclasses.LabelsList)
        protoclasses.LabelsProto.LabelsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclasses.LabelsProto.LabelsList.class, protoclasses.LabelsProto.LabelsList.Builder.class);
      }

      // Construct using protoclasses.LabelsProto.LabelsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLabelsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclasses.LabelsProto.internal_static_protoclasses_LabelsList_descriptor;
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelsList getDefaultInstanceForType() {
        return protoclasses.LabelsProto.LabelsList.getDefaultInstance();
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelsList build() {
        protoclasses.LabelsProto.LabelsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoclasses.LabelsProto.LabelsList buildPartial() {
        protoclasses.LabelsProto.LabelsList result = new protoclasses.LabelsProto.LabelsList(this);
        int from_bitField0_ = bitField0_;
        if (labelsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            labels_ = java.util.Collections.unmodifiableList(labels_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.labels_ = labels_;
        } else {
          result.labels_ = labelsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclasses.LabelsProto.LabelsList) {
          return mergeFrom((protoclasses.LabelsProto.LabelsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclasses.LabelsProto.LabelsList other) {
        if (other == protoclasses.LabelsProto.LabelsList.getDefaultInstance()) return this;
        if (labelsBuilder_ == null) {
          if (!other.labels_.isEmpty()) {
            if (labels_.isEmpty()) {
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLabelsIsMutable();
              labels_.addAll(other.labels_);
            }
            onChanged();
          }
        } else {
          if (!other.labels_.isEmpty()) {
            if (labelsBuilder_.isEmpty()) {
              labelsBuilder_.dispose();
              labelsBuilder_ = null;
              labels_ = other.labels_;
              bitField0_ = (bitField0_ & ~0x00000001);
              labelsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLabelsFieldBuilder() : null;
            } else {
              labelsBuilder_.addAllMessages(other.labels_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclasses.LabelsProto.LabelsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclasses.LabelsProto.LabelsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protoclasses.LabelsProto.LabelMessage> labels_ =
        java.util.Collections.emptyList();
      private void ensureLabelsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          labels_ = new java.util.ArrayList<protoclasses.LabelsProto.LabelMessage>(labels_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoclasses.LabelsProto.LabelMessage, protoclasses.LabelsProto.LabelMessage.Builder, protoclasses.LabelsProto.LabelMessageOrBuilder> labelsBuilder_;

      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public java.util.List<protoclasses.LabelsProto.LabelMessage> getLabelsList() {
        if (labelsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(labels_);
        } else {
          return labelsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public int getLabelsCount() {
        if (labelsBuilder_ == null) {
          return labels_.size();
        } else {
          return labelsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public protoclasses.LabelsProto.LabelMessage getLabels(int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);
        } else {
          return labelsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder setLabels(
          int index, protoclasses.LabelsProto.LabelMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.set(index, value);
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder setLabels(
          int index, protoclasses.LabelsProto.LabelMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.set(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder addLabels(protoclasses.LabelsProto.LabelMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder addLabels(
          int index, protoclasses.LabelsProto.LabelMessage value) {
        if (labelsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLabelsIsMutable();
          labels_.add(index, value);
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder addLabels(
          protoclasses.LabelsProto.LabelMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder addLabels(
          int index, protoclasses.LabelsProto.LabelMessage.Builder builderForValue) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.add(index, builderForValue.build());
          onChanged();
        } else {
          labelsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder addAllLabels(
          java.lang.Iterable<? extends protoclasses.LabelsProto.LabelMessage> values) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, labels_);
          onChanged();
        } else {
          labelsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder clearLabels() {
        if (labelsBuilder_ == null) {
          labels_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          labelsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public Builder removeLabels(int index) {
        if (labelsBuilder_ == null) {
          ensureLabelsIsMutable();
          labels_.remove(index);
          onChanged();
        } else {
          labelsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public protoclasses.LabelsProto.LabelMessage.Builder getLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public protoclasses.LabelsProto.LabelMessageOrBuilder getLabelsOrBuilder(
          int index) {
        if (labelsBuilder_ == null) {
          return labels_.get(index);  } else {
          return labelsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public java.util.List<? extends protoclasses.LabelsProto.LabelMessageOrBuilder> 
           getLabelsOrBuilderList() {
        if (labelsBuilder_ != null) {
          return labelsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(labels_);
        }
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public protoclasses.LabelsProto.LabelMessage.Builder addLabelsBuilder() {
        return getLabelsFieldBuilder().addBuilder(
            protoclasses.LabelsProto.LabelMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public protoclasses.LabelsProto.LabelMessage.Builder addLabelsBuilder(
          int index) {
        return getLabelsFieldBuilder().addBuilder(
            index, protoclasses.LabelsProto.LabelMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclasses.LabelMessage labels = 1;</code>
       */
      public java.util.List<protoclasses.LabelsProto.LabelMessage.Builder> 
           getLabelsBuilderList() {
        return getLabelsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoclasses.LabelsProto.LabelMessage, protoclasses.LabelsProto.LabelMessage.Builder, protoclasses.LabelsProto.LabelMessageOrBuilder> 
          getLabelsFieldBuilder() {
        if (labelsBuilder_ == null) {
          labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protoclasses.LabelsProto.LabelMessage, protoclasses.LabelsProto.LabelMessage.Builder, protoclasses.LabelsProto.LabelMessageOrBuilder>(
                  labels_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          labels_ = null;
        }
        return labelsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoclasses.LabelsList)
    }

    // @@protoc_insertion_point(class_scope:protoclasses.LabelsList)
    private static final protoclasses.LabelsProto.LabelsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoclasses.LabelsProto.LabelsList();
    }

    public static protoclasses.LabelsProto.LabelsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LabelsList>
        PARSER = new com.google.protobuf.AbstractParser<LabelsList>() {
      @java.lang.Override
      public LabelsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LabelsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LabelsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LabelsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoclasses.LabelsProto.LabelsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclasses_LabelMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoclasses_LabelMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclasses_LabelsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoclasses_LabelsList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014labels.proto\022\014protoclasses\"X\n\014LabelMes" +
      "sage\022\023\n\tint_label\030\001 \001(\004H\000\022\030\n\016symbolic_la" +
      "bel\030\002 \001(\tH\000\022\020\n\010label_id\030\003 \001(\005B\007\n\005label\"8" +
      "\n\nLabelsList\022*\n\006labels\030\001 \003(\0132\032.protoclas" +
      "ses.LabelMessageB\rB\013LabelsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protoclasses_LabelMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoclasses_LabelMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoclasses_LabelMessage_descriptor,
        new java.lang.String[] { "IntLabel", "SymbolicLabel", "LabelId", "Label", });
    internal_static_protoclasses_LabelsList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoclasses_LabelsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoclasses_LabelsList_descriptor,
        new java.lang.String[] { "Labels", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
