// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mnemonic.proto

package protoclasses;

public final class MnemonicProto {
  private MnemonicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MnemonicMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoclasses.MnemonicMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mnemonic = 1;</code>
     * @return The mnemonic.
     */
    java.lang.String getMnemonic();
    /**
     * <code>string mnemonic = 1;</code>
     * @return The bytes for mnemonic.
     */
    com.google.protobuf.ByteString
        getMnemonicBytes();

    /**
     * <code>int32 mnemonic_id = 2;</code>
     * @return The mnemonicId.
     */
    int getMnemonicId();
  }
  /**
   * Protobuf type {@code protoclasses.MnemonicMessage}
   */
  public  static final class MnemonicMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoclasses.MnemonicMessage)
      MnemonicMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MnemonicMessage.newBuilder() to construct.
    private MnemonicMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MnemonicMessage() {
      mnemonic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MnemonicMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MnemonicMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mnemonic_ = s;
              break;
            }
            case 16: {

              mnemonicId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclasses.MnemonicProto.MnemonicMessage.class, protoclasses.MnemonicProto.MnemonicMessage.Builder.class);
    }

    public static final int MNEMONIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object mnemonic_;
    /**
     * <code>string mnemonic = 1;</code>
     * @return The mnemonic.
     */
    public java.lang.String getMnemonic() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mnemonic_ = s;
        return s;
      }
    }
    /**
     * <code>string mnemonic = 1;</code>
     * @return The bytes for mnemonic.
     */
    public com.google.protobuf.ByteString
        getMnemonicBytes() {
      java.lang.Object ref = mnemonic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnemonic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MNEMONIC_ID_FIELD_NUMBER = 2;
    private int mnemonicId_;
    /**
     * <code>int32 mnemonic_id = 2;</code>
     * @return The mnemonicId.
     */
    public int getMnemonicId() {
      return mnemonicId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMnemonicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mnemonic_);
      }
      if (mnemonicId_ != 0) {
        output.writeInt32(2, mnemonicId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMnemonicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mnemonic_);
      }
      if (mnemonicId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, mnemonicId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoclasses.MnemonicProto.MnemonicMessage)) {
        return super.equals(obj);
      }
      protoclasses.MnemonicProto.MnemonicMessage other = (protoclasses.MnemonicProto.MnemonicMessage) obj;

      if (!getMnemonic()
          .equals(other.getMnemonic())) return false;
      if (getMnemonicId()
          != other.getMnemonicId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MNEMONIC_FIELD_NUMBER;
      hash = (53 * hash) + getMnemonic().hashCode();
      hash = (37 * hash) + MNEMONIC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMnemonicId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoclasses.MnemonicProto.MnemonicMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclasses.MnemonicMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoclasses.MnemonicMessage)
        protoclasses.MnemonicProto.MnemonicMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclasses.MnemonicProto.MnemonicMessage.class, protoclasses.MnemonicProto.MnemonicMessage.Builder.class);
      }

      // Construct using protoclasses.MnemonicProto.MnemonicMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mnemonic_ = "";

        mnemonicId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicMessage_descriptor;
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicMessage getDefaultInstanceForType() {
        return protoclasses.MnemonicProto.MnemonicMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicMessage build() {
        protoclasses.MnemonicProto.MnemonicMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicMessage buildPartial() {
        protoclasses.MnemonicProto.MnemonicMessage result = new protoclasses.MnemonicProto.MnemonicMessage(this);
        result.mnemonic_ = mnemonic_;
        result.mnemonicId_ = mnemonicId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclasses.MnemonicProto.MnemonicMessage) {
          return mergeFrom((protoclasses.MnemonicProto.MnemonicMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclasses.MnemonicProto.MnemonicMessage other) {
        if (other == protoclasses.MnemonicProto.MnemonicMessage.getDefaultInstance()) return this;
        if (!other.getMnemonic().isEmpty()) {
          mnemonic_ = other.mnemonic_;
          onChanged();
        }
        if (other.getMnemonicId() != 0) {
          setMnemonicId(other.getMnemonicId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclasses.MnemonicProto.MnemonicMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclasses.MnemonicProto.MnemonicMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mnemonic_ = "";
      /**
       * <code>string mnemonic = 1;</code>
       * @return The mnemonic.
       */
      public java.lang.String getMnemonic() {
        java.lang.Object ref = mnemonic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mnemonic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mnemonic = 1;</code>
       * @return The bytes for mnemonic.
       */
      public com.google.protobuf.ByteString
          getMnemonicBytes() {
        java.lang.Object ref = mnemonic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnemonic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mnemonic = 1;</code>
       * @param value The mnemonic to set.
       * @return This builder for chaining.
       */
      public Builder setMnemonic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mnemonic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mnemonic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMnemonic() {
        
        mnemonic_ = getDefaultInstance().getMnemonic();
        onChanged();
        return this;
      }
      /**
       * <code>string mnemonic = 1;</code>
       * @param value The bytes for mnemonic to set.
       * @return This builder for chaining.
       */
      public Builder setMnemonicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mnemonic_ = value;
        onChanged();
        return this;
      }

      private int mnemonicId_ ;
      /**
       * <code>int32 mnemonic_id = 2;</code>
       * @return The mnemonicId.
       */
      public int getMnemonicId() {
        return mnemonicId_;
      }
      /**
       * <code>int32 mnemonic_id = 2;</code>
       * @param value The mnemonicId to set.
       * @return This builder for chaining.
       */
      public Builder setMnemonicId(int value) {
        
        mnemonicId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mnemonic_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMnemonicId() {
        
        mnemonicId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoclasses.MnemonicMessage)
    }

    // @@protoc_insertion_point(class_scope:protoclasses.MnemonicMessage)
    private static final protoclasses.MnemonicProto.MnemonicMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoclasses.MnemonicProto.MnemonicMessage();
    }

    public static protoclasses.MnemonicProto.MnemonicMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MnemonicMessage>
        PARSER = new com.google.protobuf.AbstractParser<MnemonicMessage>() {
      @java.lang.Override
      public MnemonicMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MnemonicMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MnemonicMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MnemonicMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoclasses.MnemonicProto.MnemonicMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MnemonicsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoclasses.MnemonicsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    java.util.List<protoclasses.MnemonicProto.MnemonicMessage> 
        getMnemonicsList();
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    protoclasses.MnemonicProto.MnemonicMessage getMnemonics(int index);
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    int getMnemonicsCount();
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    java.util.List<? extends protoclasses.MnemonicProto.MnemonicMessageOrBuilder> 
        getMnemonicsOrBuilderList();
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    protoclasses.MnemonicProto.MnemonicMessageOrBuilder getMnemonicsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoclasses.MnemonicsList}
   */
  public  static final class MnemonicsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoclasses.MnemonicsList)
      MnemonicsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MnemonicsList.newBuilder() to construct.
    private MnemonicsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MnemonicsList() {
      mnemonics_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MnemonicsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MnemonicsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mnemonics_ = new java.util.ArrayList<protoclasses.MnemonicProto.MnemonicMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              mnemonics_.add(
                  input.readMessage(protoclasses.MnemonicProto.MnemonicMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          mnemonics_ = java.util.Collections.unmodifiableList(mnemonics_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoclasses.MnemonicProto.MnemonicsList.class, protoclasses.MnemonicProto.MnemonicsList.Builder.class);
    }

    public static final int MNEMONICS_FIELD_NUMBER = 1;
    private java.util.List<protoclasses.MnemonicProto.MnemonicMessage> mnemonics_;
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    public java.util.List<protoclasses.MnemonicProto.MnemonicMessage> getMnemonicsList() {
      return mnemonics_;
    }
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    public java.util.List<? extends protoclasses.MnemonicProto.MnemonicMessageOrBuilder> 
        getMnemonicsOrBuilderList() {
      return mnemonics_;
    }
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    public int getMnemonicsCount() {
      return mnemonics_.size();
    }
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    public protoclasses.MnemonicProto.MnemonicMessage getMnemonics(int index) {
      return mnemonics_.get(index);
    }
    /**
     * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
     */
    public protoclasses.MnemonicProto.MnemonicMessageOrBuilder getMnemonicsOrBuilder(
        int index) {
      return mnemonics_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < mnemonics_.size(); i++) {
        output.writeMessage(1, mnemonics_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < mnemonics_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mnemonics_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoclasses.MnemonicProto.MnemonicsList)) {
        return super.equals(obj);
      }
      protoclasses.MnemonicProto.MnemonicsList other = (protoclasses.MnemonicProto.MnemonicsList) obj;

      if (!getMnemonicsList()
          .equals(other.getMnemonicsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMnemonicsCount() > 0) {
        hash = (37 * hash) + MNEMONICS_FIELD_NUMBER;
        hash = (53 * hash) + getMnemonicsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoclasses.MnemonicProto.MnemonicsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoclasses.MnemonicProto.MnemonicsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoclasses.MnemonicsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoclasses.MnemonicsList)
        protoclasses.MnemonicProto.MnemonicsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoclasses.MnemonicProto.MnemonicsList.class, protoclasses.MnemonicProto.MnemonicsList.Builder.class);
      }

      // Construct using protoclasses.MnemonicProto.MnemonicsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMnemonicsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mnemonicsBuilder_ == null) {
          mnemonics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mnemonicsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoclasses.MnemonicProto.internal_static_protoclasses_MnemonicsList_descriptor;
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicsList getDefaultInstanceForType() {
        return protoclasses.MnemonicProto.MnemonicsList.getDefaultInstance();
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicsList build() {
        protoclasses.MnemonicProto.MnemonicsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoclasses.MnemonicProto.MnemonicsList buildPartial() {
        protoclasses.MnemonicProto.MnemonicsList result = new protoclasses.MnemonicProto.MnemonicsList(this);
        int from_bitField0_ = bitField0_;
        if (mnemonicsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            mnemonics_ = java.util.Collections.unmodifiableList(mnemonics_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mnemonics_ = mnemonics_;
        } else {
          result.mnemonics_ = mnemonicsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoclasses.MnemonicProto.MnemonicsList) {
          return mergeFrom((protoclasses.MnemonicProto.MnemonicsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoclasses.MnemonicProto.MnemonicsList other) {
        if (other == protoclasses.MnemonicProto.MnemonicsList.getDefaultInstance()) return this;
        if (mnemonicsBuilder_ == null) {
          if (!other.mnemonics_.isEmpty()) {
            if (mnemonics_.isEmpty()) {
              mnemonics_ = other.mnemonics_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMnemonicsIsMutable();
              mnemonics_.addAll(other.mnemonics_);
            }
            onChanged();
          }
        } else {
          if (!other.mnemonics_.isEmpty()) {
            if (mnemonicsBuilder_.isEmpty()) {
              mnemonicsBuilder_.dispose();
              mnemonicsBuilder_ = null;
              mnemonics_ = other.mnemonics_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mnemonicsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMnemonicsFieldBuilder() : null;
            } else {
              mnemonicsBuilder_.addAllMessages(other.mnemonics_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoclasses.MnemonicProto.MnemonicsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoclasses.MnemonicProto.MnemonicsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protoclasses.MnemonicProto.MnemonicMessage> mnemonics_ =
        java.util.Collections.emptyList();
      private void ensureMnemonicsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mnemonics_ = new java.util.ArrayList<protoclasses.MnemonicProto.MnemonicMessage>(mnemonics_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoclasses.MnemonicProto.MnemonicMessage, protoclasses.MnemonicProto.MnemonicMessage.Builder, protoclasses.MnemonicProto.MnemonicMessageOrBuilder> mnemonicsBuilder_;

      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public java.util.List<protoclasses.MnemonicProto.MnemonicMessage> getMnemonicsList() {
        if (mnemonicsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mnemonics_);
        } else {
          return mnemonicsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public int getMnemonicsCount() {
        if (mnemonicsBuilder_ == null) {
          return mnemonics_.size();
        } else {
          return mnemonicsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public protoclasses.MnemonicProto.MnemonicMessage getMnemonics(int index) {
        if (mnemonicsBuilder_ == null) {
          return mnemonics_.get(index);
        } else {
          return mnemonicsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder setMnemonics(
          int index, protoclasses.MnemonicProto.MnemonicMessage value) {
        if (mnemonicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMnemonicsIsMutable();
          mnemonics_.set(index, value);
          onChanged();
        } else {
          mnemonicsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder setMnemonics(
          int index, protoclasses.MnemonicProto.MnemonicMessage.Builder builderForValue) {
        if (mnemonicsBuilder_ == null) {
          ensureMnemonicsIsMutable();
          mnemonics_.set(index, builderForValue.build());
          onChanged();
        } else {
          mnemonicsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder addMnemonics(protoclasses.MnemonicProto.MnemonicMessage value) {
        if (mnemonicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMnemonicsIsMutable();
          mnemonics_.add(value);
          onChanged();
        } else {
          mnemonicsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder addMnemonics(
          int index, protoclasses.MnemonicProto.MnemonicMessage value) {
        if (mnemonicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMnemonicsIsMutable();
          mnemonics_.add(index, value);
          onChanged();
        } else {
          mnemonicsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder addMnemonics(
          protoclasses.MnemonicProto.MnemonicMessage.Builder builderForValue) {
        if (mnemonicsBuilder_ == null) {
          ensureMnemonicsIsMutable();
          mnemonics_.add(builderForValue.build());
          onChanged();
        } else {
          mnemonicsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder addMnemonics(
          int index, protoclasses.MnemonicProto.MnemonicMessage.Builder builderForValue) {
        if (mnemonicsBuilder_ == null) {
          ensureMnemonicsIsMutable();
          mnemonics_.add(index, builderForValue.build());
          onChanged();
        } else {
          mnemonicsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder addAllMnemonics(
          java.lang.Iterable<? extends protoclasses.MnemonicProto.MnemonicMessage> values) {
        if (mnemonicsBuilder_ == null) {
          ensureMnemonicsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mnemonics_);
          onChanged();
        } else {
          mnemonicsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder clearMnemonics() {
        if (mnemonicsBuilder_ == null) {
          mnemonics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mnemonicsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public Builder removeMnemonics(int index) {
        if (mnemonicsBuilder_ == null) {
          ensureMnemonicsIsMutable();
          mnemonics_.remove(index);
          onChanged();
        } else {
          mnemonicsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public protoclasses.MnemonicProto.MnemonicMessage.Builder getMnemonicsBuilder(
          int index) {
        return getMnemonicsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public protoclasses.MnemonicProto.MnemonicMessageOrBuilder getMnemonicsOrBuilder(
          int index) {
        if (mnemonicsBuilder_ == null) {
          return mnemonics_.get(index);  } else {
          return mnemonicsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public java.util.List<? extends protoclasses.MnemonicProto.MnemonicMessageOrBuilder> 
           getMnemonicsOrBuilderList() {
        if (mnemonicsBuilder_ != null) {
          return mnemonicsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mnemonics_);
        }
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public protoclasses.MnemonicProto.MnemonicMessage.Builder addMnemonicsBuilder() {
        return getMnemonicsFieldBuilder().addBuilder(
            protoclasses.MnemonicProto.MnemonicMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public protoclasses.MnemonicProto.MnemonicMessage.Builder addMnemonicsBuilder(
          int index) {
        return getMnemonicsFieldBuilder().addBuilder(
            index, protoclasses.MnemonicProto.MnemonicMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .protoclasses.MnemonicMessage mnemonics = 1;</code>
       */
      public java.util.List<protoclasses.MnemonicProto.MnemonicMessage.Builder> 
           getMnemonicsBuilderList() {
        return getMnemonicsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoclasses.MnemonicProto.MnemonicMessage, protoclasses.MnemonicProto.MnemonicMessage.Builder, protoclasses.MnemonicProto.MnemonicMessageOrBuilder> 
          getMnemonicsFieldBuilder() {
        if (mnemonicsBuilder_ == null) {
          mnemonicsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protoclasses.MnemonicProto.MnemonicMessage, protoclasses.MnemonicProto.MnemonicMessage.Builder, protoclasses.MnemonicProto.MnemonicMessageOrBuilder>(
                  mnemonics_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          mnemonics_ = null;
        }
        return mnemonicsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoclasses.MnemonicsList)
    }

    // @@protoc_insertion_point(class_scope:protoclasses.MnemonicsList)
    private static final protoclasses.MnemonicProto.MnemonicsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoclasses.MnemonicProto.MnemonicsList();
    }

    public static protoclasses.MnemonicProto.MnemonicsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MnemonicsList>
        PARSER = new com.google.protobuf.AbstractParser<MnemonicsList>() {
      @java.lang.Override
      public MnemonicsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MnemonicsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MnemonicsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MnemonicsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoclasses.MnemonicProto.MnemonicsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclasses_MnemonicMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoclasses_MnemonicMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoclasses_MnemonicsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoclasses_MnemonicsList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016mnemonic.proto\022\014protoclasses\"8\n\017Mnemon" +
      "icMessage\022\020\n\010mnemonic\030\001 \001(\t\022\023\n\013mnemonic_" +
      "id\030\002 \001(\005\"A\n\rMnemonicsList\0220\n\tmnemonics\030\001" +
      " \003(\0132\035.protoclasses.MnemonicMessageB\017B\rM" +
      "nemonicProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protoclasses_MnemonicMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoclasses_MnemonicMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoclasses_MnemonicMessage_descriptor,
        new java.lang.String[] { "Mnemonic", "MnemonicId", });
    internal_static_protoclasses_MnemonicsList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoclasses_MnemonicsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoclasses_MnemonicsList_descriptor,
        new java.lang.String[] { "Mnemonics", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
