# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kindofdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kindofdata.proto',
  package='protoclasses',
  syntax='proto3',
  serialized_options=_b('B\nKindOfData'),
  serialized_pb=_b('\n\x10kindofdata.proto\x12\x0cprotoclasses*z\n\x04Kind\x12\x0b\n\x07\x44\x45\x46INED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05\x41RRAY\x10\x02\x12\x0c\n\x08\x43ONSTANT\x10\x03\x12\x0b\n\x07\x44YNAMIC\x10\x04\x12\x0b\n\x07POINTER\x10\x05\x12\r\n\tSTRUCTURE\x10\x06\x12\t\n\x05UNION\x10\x07\x12\x0c\n\x08VOLATILE\x10\x08\x42\x0c\x42\nKindOfDatab\x06proto3')
)

_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='protoclasses.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARRAY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DYNAMIC', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRUCTURE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNION', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOLATILE', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=34,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_KIND)

Kind = enum_type_wrapper.EnumTypeWrapper(_KIND)
DEFINED = 0
STRING = 1
ARRAY = 2
CONSTANT = 3
DYNAMIC = 4
POINTER = 5
STRUCTURE = 6
UNION = 7
VOLATILE = 8


DESCRIPTOR.enum_types_by_name['Kind'] = _KIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
