# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labels.proto',
  package='protoclasses',
  syntax='proto3',
  serialized_options=b'B\013LabelsProto',
  serialized_pb=b'\n\x0clabels.proto\x12\x0cprotoclasses\"X\n\x0cLabelMessage\x12\x13\n\tint_label\x18\x01 \x01(\x04H\x00\x12\x18\n\x0esymbolic_label\x18\x02 \x01(\tH\x00\x12\x10\n\x08label_id\x18\x03 \x01(\x05\x42\x07\n\x05label\"8\n\nLabelsList\x12*\n\x06labels\x18\x01 \x03(\x0b\x32\x1a.protoclasses.LabelMessageB\rB\x0bLabelsProtob\x06proto3'
)




_LABELMESSAGE = _descriptor.Descriptor(
  name='LabelMessage',
  full_name='protoclasses.LabelMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_label', full_name='protoclasses.LabelMessage.int_label', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbolic_label', full_name='protoclasses.LabelMessage.symbolic_label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_id', full_name='protoclasses.LabelMessage.label_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='label', full_name='protoclasses.LabelMessage.label',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=118,
)


_LABELSLIST = _descriptor.Descriptor(
  name='LabelsList',
  full_name='protoclasses.LabelsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='protoclasses.LabelsList.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=176,
)

_LABELMESSAGE.oneofs_by_name['label'].fields.append(
  _LABELMESSAGE.fields_by_name['int_label'])
_LABELMESSAGE.fields_by_name['int_label'].containing_oneof = _LABELMESSAGE.oneofs_by_name['label']
_LABELMESSAGE.oneofs_by_name['label'].fields.append(
  _LABELMESSAGE.fields_by_name['symbolic_label'])
_LABELMESSAGE.fields_by_name['symbolic_label'].containing_oneof = _LABELMESSAGE.oneofs_by_name['label']
_LABELSLIST.fields_by_name['labels'].message_type = _LABELMESSAGE
DESCRIPTOR.message_types_by_name['LabelMessage'] = _LABELMESSAGE
DESCRIPTOR.message_types_by_name['LabelsList'] = _LABELSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelMessage = _reflection.GeneratedProtocolMessageType('LabelMessage', (_message.Message,), {
  'DESCRIPTOR' : _LABELMESSAGE,
  '__module__' : 'labels_pb2'
  # @@protoc_insertion_point(class_scope:protoclasses.LabelMessage)
  })
_sym_db.RegisterMessage(LabelMessage)

LabelsList = _reflection.GeneratedProtocolMessageType('LabelsList', (_message.Message,), {
  'DESCRIPTOR' : _LABELSLIST,
  '__module__' : 'labels_pb2'
  # @@protoc_insertion_point(class_scope:protoclasses.LabelsList)
  })
_sym_db.RegisterMessage(LabelsList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
