# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: symbols.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='symbols.proto',
  package='protoclasses',
  syntax='proto3',
  serialized_options=b'B\014SymbolsProto',
  serialized_pb=b'\n\rsymbols.proto\x12\x0cprotoclasses\"\xd1\x03\n\rSymbolMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0clong_address\x18\x02 \x01(\x04H\x00\x12\x1a\n\x10symbolic_address\x18\x03 \x01(\tH\x00\x12;\n\x04type\x18\x04 \x01(\x0e\x32-.protoclasses.SymbolMessage.SymbolMessageType\x12\x11\n\tnamespace\x18\x05 \x01(\t\x12\x36\n\x06source\x18\x06 \x01(\x0e\x32&.protoclasses.SymbolMessage.SourceType\x12\x14\n\x0creference_id\x18\x08 \x03(\x05\"\x8b\x01\n\x11SymbolMessageType\x12\x08\n\x04NULL\x10\x00\x12\t\n\x05LABEL\x10\x01\x12\x0b\n\x07LIBRARY\x10\x02\x12\r\n\tNAMESPACE\x10\x03\x12\t\n\x05\x43LASS\x10\x04\x12\x0c\n\x08\x46UNCTION\x10\x05\x12\r\n\tPARAMETER\x10\x06\x12\r\n\tLOCAL_VAR\x10\x07\x12\x0e\n\nGLOBAL_VAR\x10\x08\"G\n\nSourceType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0c\n\x08\x41NALYSIS\x10\x01\x12\x0c\n\x08IMPORTED\x10\x02\x12\x10\n\x0cUSER_DEFINED\x10\x03\x42\t\n\x07\x61\x64\x64ress\";\n\x0bSymbolsList\x12,\n\x07symbols\x18\x01 \x03(\x0b\x32\x1b.protoclasses.SymbolMessageB\x0e\x42\x0cSymbolsProtob\x06proto3'
)



_SYMBOLMESSAGE_SYMBOLMESSAGETYPE = _descriptor.EnumDescriptor(
  name='SymbolMessageType',
  full_name='protoclasses.SymbolMessage.SymbolMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LABEL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIBRARY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAMESPACE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLASS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUNCTION', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL_VAR', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBAL_VAR', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=274,
  serialized_end=413,
)
_sym_db.RegisterEnumDescriptor(_SYMBOLMESSAGE_SYMBOLMESSAGETYPE)

_SYMBOLMESSAGE_SOURCETYPE = _descriptor.EnumDescriptor(
  name='SourceType',
  full_name='protoclasses.SymbolMessage.SourceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANALYSIS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPORTED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_DEFINED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=415,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_SYMBOLMESSAGE_SOURCETYPE)


_SYMBOLMESSAGE = _descriptor.Descriptor(
  name='SymbolMessage',
  full_name='protoclasses.SymbolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protoclasses.SymbolMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_address', full_name='protoclasses.SymbolMessage.long_address', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbolic_address', full_name='protoclasses.SymbolMessage.symbolic_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protoclasses.SymbolMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='protoclasses.SymbolMessage.namespace', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='protoclasses.SymbolMessage.source', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reference_id', full_name='protoclasses.SymbolMessage.reference_id', index=6,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYMBOLMESSAGE_SYMBOLMESSAGETYPE,
    _SYMBOLMESSAGE_SOURCETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='address', full_name='protoclasses.SymbolMessage.address',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=32,
  serialized_end=497,
)


_SYMBOLSLIST = _descriptor.Descriptor(
  name='SymbolsList',
  full_name='protoclasses.SymbolsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbols', full_name='protoclasses.SymbolsList.symbols', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=558,
)

_SYMBOLMESSAGE.fields_by_name['type'].enum_type = _SYMBOLMESSAGE_SYMBOLMESSAGETYPE
_SYMBOLMESSAGE.fields_by_name['source'].enum_type = _SYMBOLMESSAGE_SOURCETYPE
_SYMBOLMESSAGE_SYMBOLMESSAGETYPE.containing_type = _SYMBOLMESSAGE
_SYMBOLMESSAGE_SOURCETYPE.containing_type = _SYMBOLMESSAGE
_SYMBOLMESSAGE.oneofs_by_name['address'].fields.append(
  _SYMBOLMESSAGE.fields_by_name['long_address'])
_SYMBOLMESSAGE.fields_by_name['long_address'].containing_oneof = _SYMBOLMESSAGE.oneofs_by_name['address']
_SYMBOLMESSAGE.oneofs_by_name['address'].fields.append(
  _SYMBOLMESSAGE.fields_by_name['symbolic_address'])
_SYMBOLMESSAGE.fields_by_name['symbolic_address'].containing_oneof = _SYMBOLMESSAGE.oneofs_by_name['address']
_SYMBOLSLIST.fields_by_name['symbols'].message_type = _SYMBOLMESSAGE
DESCRIPTOR.message_types_by_name['SymbolMessage'] = _SYMBOLMESSAGE
DESCRIPTOR.message_types_by_name['SymbolsList'] = _SYMBOLSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymbolMessage = _reflection.GeneratedProtocolMessageType('SymbolMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLMESSAGE,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:protoclasses.SymbolMessage)
  })
_sym_db.RegisterMessage(SymbolMessage)

SymbolsList = _reflection.GeneratedProtocolMessageType('SymbolsList', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLSLIST,
  '__module__' : 'symbols_pb2'
  # @@protoc_insertion_point(class_scope:protoclasses.SymbolsList)
  })
_sym_db.RegisterMessage(SymbolsList)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
